name: dbt CI

on:
  pull_request:
    branches:
      - main

jobs:
  dbt-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dbt
        run: pip install dbt-bigquery

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up dbt profile
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          default:
            target: dev
            outputs:
              dev:
                type: bigquery
                method: service-account-json
                project: hr-analytics-portfolio-495323
                dataset: dev
                threads: 4
                location: US
                keyfile_json: ${{ secrets.GCP_SA_KEY }}
          EOF

      - name: Run dbt build
        run: dbt build --profiles-dir ~/.dbt
